name: Comment on Pull Request

on:
  pull_request:
    types: [opened]

permissions:
  issues: write
  pull-requests: write
  
jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add a comment to the pull request
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Thank you for your pull request! We will review it shortly. Password to complete mission: IgN7lSkvxizlP2lU8r5uaTjRILCSnR
