on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Hello! :wave:
            This is the password: IgN7lSkvxizlP2lU8r5uaTjRILCSnR
          create_if_not_exists: true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}  # Use the personal access token
