on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    permissions:
      pull-requests: write  # Ensure the token has write permissions for pull requests
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Hello! :wave:
            This is the password: IgN7lSkvxizlP2lU8r5uaTjRILCSnR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure the token is referenced correctly
